version: "3"

services:

  haproxy:
    container_name: lb
    image: haproxy:latest
    ports:
      - "8080:8080"
      - "8085:8085"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"